package converter.common;

public enum CodePlacement {

	BOTNAME, WAL_DOCUMENTATION, API_DOCUMENTATION, MAIN, DEF_INPUT_VARS, DEF_OUTPUT_VARS, URLPARAMS, QUERYPARAMS, API_INPUT_PARAMS, API_OUTPUT_PARAMS
}
