package converter.common;

public enum CodePlacement {

	BOTNAME, WAL_DOCUMENTATION, API_DOCUMENTATION, MAIN, DEF_INPUT_VARS, DEF_OUTPUT_VARS, DEF_INTERNAL_VARS, URLPARAMS, QUERYPARAMS, API_INPUT_PARAMS, API_OUTPUT_PARAMS, API_SYSTEM, INVOKE_URL, GET_RESULT_URL,  CALLODM
}
